name: Build APK

on:
  push:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Setup pgs4a
      run: |
        git clone https://github.com/pygame/python-for-android
        cd python-for-android
        ./android.py installsdk

    - name: Build APK
      run: |
        cd python-for-android
        ./android.py --package io.clangen.clangen --name "Clangen" --version 1.0 --dir ../ --permission INTERNET --permission WRITE_EXTERNAL_STORAGE --permission READ_EXTERNAL_STORAGE --orientation landscape debug
        mv bin/Clangen-1.0-debug.apk ../Clangen.apk

    - name: Upload APK
      uses: actions/upload-artifact@v2
      with:
        name: Clangen
        path: Clangen.apk
